# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 76f198c3f9cab48a2a1559bfef892122cb1143504157e8d81bfabd7c52e72c9c65bb45b7ed34dbe46092de66351d0b45fbb7c2514236c9e0ecdcca6158962a0f

test:
  secret_key_base: b9464735d338f6b81f12f70dc86edb091be4a55e9df3a187882a31b253efdcd9b5fe8f6168c287537151fab26399c854498ee76b3507054bdeb0b323c29a0eff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
